package UI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import ConnectionUtility.DatabaseConnection;



/**
 *
 * @author Admin
 */
public class TacGiaForm extends javax.swing.JFrame {
       public static Connection getConnection() {
    try {
        // Tải driver MySQL
        Class.forName("com.mysql.cj.jdbc.Driver");

        // Kết nối tới cơ sở dữ liệu MySQL
        String url = "jdbc:mysql://localhost:3306/thuviendb";
        String user = "root";
        String password = "";

        // Trả về kết nối
        return DriverManager.getConnection(url, user, password);

    } catch (ClassNotFoundException e) {
        System.err.println("Lỗi: Không tìm thấy driver MySQL!");
        e.printStackTrace();
    } catch (SQLException e) {
        System.err.println("Lỗi khi kết nối tới cơ sở dữ liệu: " + e.getMessage());
        e.printStackTrace();
    }

    return null;  // Trả về null nếu không thể kết nối
}




    /**
     * Creates new form TacGiaForm
     */
    public TacGiaForm() {
        initComponents();loadData();
    }
    private void loadData() {
    try {
        // Sử dụng DatabaseConnection để kết nối
        Connection conn = DatabaseConnection.getConnection();
        String sql = "SELECT * FROM tacgia";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        // Chuẩn bị model cho bảng
        DefaultTableModel model = (DefaultTableModel) tbTG.getModel();
        model.setRowCount(0);  // Xóa dữ liệu trong bảng

        while (rs.next()) {
            String maTacGia = rs.getString("MaTacGia");
            String tenTacGia = rs.getString("TenTacGia");
            model.addRow(new Object[]{maTacGia, tenTacGia});
        }

        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Lỗi khi tải dữ liệu: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTG = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        mTG_DCM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tTG_DCM = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN TÁC GIẢ");

        tbTG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "MÃ TÁC GIẢ", "TÊN TÁC GIẢ"
            }
        ));
        jScrollPane1.setViewportView(tbTG);
        if (tbTG.getColumnModel().getColumnCount() > 0) {
            tbTG.getColumnModel().getColumn(0).setHeaderValue("MÃ TÁC GIẢ");
            tbTG.getColumnModel().getColumn(1).setHeaderValue("TÊN TÁC GIẢ");
        }

        jLabel2.setText("Mã Tác giả:");

        mTG_DCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTG_DCMActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên Tác giả:");

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLammoi.setText("LÀM MỚI");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        jButton1.setText("Trang chủ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Đỗ Công Minh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnLammoi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tTG_DCM, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mTG_DCM, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel14)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel14)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mTG_DCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tTG_DCM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLammoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
try {
        Connection conn = DatabaseConnection.getConnection();
        String sql = "INSERT INTO tacgia (MaTacGia, TenTacGia) VALUES (?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, mTG_DCM.getText());
        pst.setString(2, tTG_DCM.getText());

        int rows = pst.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "Thêm thành công!");
            loadData(); // Tải lại dữ liệu bảng
        }

        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Lỗi khi thêm: " + e.getMessage());
    } // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
            if (mTG_DCM.getText().isEmpty() || tTG_DCM.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập đầy đủ thông tin!");
        return;
    }
    try {
        Connection conn = DatabaseConnection.getConnection();
        String sql = "UPDATE tacgia SET TenTacGia=? WHERE MaTacGia=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, tTG_DCM.getText());
        pst.setString(2, mTG_DCM.getText());

        int rows = pst.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "Cập nhật thành công!");
            loadData(); // Tải lại dữ liệu bảng
        } else {
            JOptionPane.showMessageDialog(null, "Không tìm thấy tác giả với mã: " + mTG_DCM.getText());
        }

        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Lỗi khi sửa: " + e.getMessage());
    }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
         if (mTG_DCM.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập mã tác giả để xóa!");
        return;
    }
    try {
        Connection conn = DatabaseConnection.getConnection();
        String sql = "DELETE FROM tacgia WHERE MaTacGia=?";
        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, mTG_DCM.getText());

        int rows = pst.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(null, "Xóa thành công!");
            loadData(); // Tải lại dữ liệu bảng
        } else {
            JOptionPane.showMessageDialog(null, "Không tìm thấy tác giả với mã: " + mTG_DCM.getText());
        }

        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Lỗi khi xóa: " + e.getMessage());
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
  mTG_DCM.setText("");
        tTG_DCM.setText("");
        tbTG.clearSelection();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLammoiActionPerformed
MainForm mainForm = new MainForm();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
    
    // Tạo và hiển thị lại MainForm
    
    mainForm.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mTG_DCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTG_DCMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mTG_DCMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TacGiaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TacGiaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TacGiaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TacGiaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TacGiaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mTG_DCM;
    private javax.swing.JTextField tTG_DCM;
    private javax.swing.JTable tbTG;
    // End of variables declaration//GEN-END:variables
}
